language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  - USE_PHP_EXTENSIONS=FALSE
  - USE_PHP_EXTENSIONS=TRUE

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls -v
